services:
  backend:
    build:
      context: .
      dockerfile: EventBookingSystem.API/Dockerfile
    ports:
      - "5050:5050"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://+:5050"
      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=EventBookingDb;User Id=sa;Password=StrongPassword123;TrustServerCertificate=True;"
    depends_on:
      - sqlserver
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_API_URL: "http://localhost:5050/api/event"
    ports:
      - "3000:80"
    environment:
      REACT_APP_API_URL: "http://localhost:5050/api/event"
    depends_on:
      - backend
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "StrongPassword123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"